// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#ifndef _ESP32_LCD_1_28_INCH_UI_H
#define _ESP32_LCD_1_28_INCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MenuScreen.h"
#include "screens/ui_WifiSettingScreen.h"
#include "screens/ui_SettingButton.h"
#include "screens/ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_1765884034);    // assets/smart-watch.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/info.png
LV_IMG_DECLARE(ui_img_untitled_png);    // assets/Untitled.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
