// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void WifiInfoEvent(lv_event_t * e);
void WifiSelected_Event(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
