// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "ui.h"

void WifiInfoEvent(lv_event_t * e)
{
	// Your code here
}

void WifiSelected_Event(lv_event_t * e)
{
	// Your code here
}
