// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "../ui.h"

void ui_comp_WifiItem_create_hook(lv_obj_t * comp)
{
}
