// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "../ui.h"

// COMPONENT WifiItem

lv_obj_t * ui_WifiItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_WifiItem;
    cui_WifiItem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_WifiItem);
    lv_obj_set_width(cui_WifiItem, lv_pct(90));
    lv_obj_set_height(cui_WifiItem, lv_pct(15));
    lv_obj_set_align(cui_WifiItem, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_WifiItem, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(cui_WifiItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Button3;
    cui_Button3 = lv_button_create(cui_WifiItem);
    lv_obj_set_width(cui_Button3, lv_pct(100));
    lv_obj_set_height(cui_Button3, lv_pct(100));
    lv_obj_set_align(cui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button3, lv_color_hex(0xBFBBBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Button3);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label4, "text");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_WIFIITEM_NUM);
    children[UI_COMP_WIFIITEM_WIFIITEM] = cui_WifiItem;
    children[UI_COMP_WIFIITEM_BUTTON3] = cui_Button3;
    children[UI_COMP_WIFIITEM_BUTTON3_LABEL4] = cui_Label4;
    lv_obj_add_event_cb(cui_WifiItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_WifiItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_WifiItem_create_hook(cui_WifiItem);
    return cui_WifiItem;
}

