// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#ifndef _UI_COMP_WIFIITEM_H
#define _UI_COMP_WIFIITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT WifiItem
#define UI_COMP_WIFIITEM_WIFIITEM 0
#define UI_COMP_WIFIITEM_BUTTON3 1
#define UI_COMP_WIFIITEM_BUTTON3_LABEL4 2
#define _UI_COMP_WIFIITEM_NUM 3
lv_obj_t * ui_WifiItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
