// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_HourLable;
extern lv_obj_t * ui_MinuteLabel;
extern lv_obj_t * ui_MonthLael;
extern lv_obj_t * ui_DateLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainScreen;
extern lv_obj_t * uic_MonthLael;
extern lv_obj_t * uic_DateLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

