// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_WifiButton;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_MainScreenButton;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_SettingButotn;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_WatchButotn;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MenuScreen;
extern lv_obj_t * uic_WifiButton;
extern lv_obj_t * uic_MainScreenButton;
extern lv_obj_t * uic_SettingButotn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

