// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "../ui.h"

lv_obj_t * uic_DateLabel;
lv_obj_t * uic_MonthLael;
lv_obj_t * uic_MainScreen;
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label2;
lv_obj_t * ui_HourLable;
lv_obj_t * ui_MinuteLabel;
lv_obj_t * ui_MonthLael;
lv_obj_t * ui_DateLabel;

// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_MainScreen, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 20);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "Monday");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_image_create(ui_MainScreen);
    lv_image_set_src(ui_Image6, &ui_img_sun_png);
    lv_obj_set_width(ui_Image6, 50);
    lv_obj_set_height(ui_Image6, 50);
    lv_obj_set_x(ui_Image6, 21);
    lv_obj_set_y(ui_Image6, -71);
    lv_obj_set_align(ui_Image6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image6, 230);

    ui_Label6 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -72);
    lv_obj_set_y(ui_Label6, 67);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "21");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -53);
    lv_obj_set_y(ui_Label2, 65);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "*C");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourLable = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_HourLable, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_HourLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLable, -10);
    lv_obj_set_y(ui_HourLable, -34);
    lv_obj_set_align(ui_HourLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourLable, "11");
    lv_obj_set_style_text_color(ui_HourLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourLable, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteLabel, 27);
    lv_obj_set_y(ui_MinuteLabel, 43);
    lv_obj_set_align(ui_MinuteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinuteLabel, "49");
    lv_obj_set_style_text_color(ui_MinuteLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinuteLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinuteLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthLael = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MonthLael, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonthLael, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonthLael, 74);
    lv_obj_set_y(ui_MonthLael, -22);
    lv_obj_set_align(ui_MonthLael, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MonthLael, "June");
    lv_obj_set_style_text_color(ui_MonthLael, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MonthLael, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MonthLael, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 58);
    lv_obj_set_y(ui_DateLabel, -42);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "13");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_MainScreen = ui_MainScreen;
    uic_MonthLael = ui_MonthLael;
    uic_DateLabel = ui_DateLabel;

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    uic_MainScreen = NULL;
    ui_MainScreen = NULL;
    ui_Label5 = NULL;
    ui_Image6 = NULL;
    ui_Label6 = NULL;
    ui_Label2 = NULL;
    ui_HourLable = NULL;
    ui_MinuteLabel = NULL;
    uic_MonthLael = NULL;
    ui_MonthLael = NULL;
    uic_DateLabel = NULL;
    ui_DateLabel = NULL;

}
