// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "../ui.h"

lv_obj_t * uic_SettingButotn;
lv_obj_t * uic_MainScreenButton;
lv_obj_t * uic_WifiButton;
lv_obj_t * uic_MenuScreen;
lv_obj_t * ui_MenuScreen;
lv_obj_t * ui_WifiButton;
lv_obj_t * ui_Image1;
lv_obj_t * ui_MainScreenButton;
lv_obj_t * ui_Image2;
lv_obj_t * ui_SettingButotn;
lv_obj_t * ui_Image3;
lv_obj_t * ui_WatchButotn;
lv_obj_t * ui_Image4;

// event funtions
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiSettingScreen_screen_init);
    }
}

void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingScreen_screen_init);
    }
}

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_WifiButton, 60);
    lv_obj_set_height(ui_WifiButton, 60);
    lv_obj_set_x(ui_WifiButton, 40);
    lv_obj_set_y(ui_WifiButton, 40);
    lv_obj_add_flag(ui_WifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiButton, lv_color_hex(0xC2C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_WifiButton);
    lv_image_set_src(ui_Image1, &ui_img_wifi_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 200);

    ui_MainScreenButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_MainScreenButton, 60);
    lv_obj_set_height(ui_MainScreenButton, 60);
    lv_obj_set_x(ui_MainScreenButton, 140);
    lv_obj_set_y(ui_MainScreenButton, 40);
    lv_obj_add_flag(ui_MainScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MainScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenButton, lv_color_hex(0xC2C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_MainScreenButton);
    lv_image_set_src(ui_Image2, &ui_img_home_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 200);

    ui_SettingButotn = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_SettingButotn, 60);
    lv_obj_set_height(ui_SettingButotn, 60);
    lv_obj_set_x(ui_SettingButotn, 140);
    lv_obj_set_y(ui_SettingButotn, 140);
    lv_obj_add_flag(ui_SettingButotn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingButotn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingButotn, lv_color_hex(0xC2C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingButotn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_SettingButotn);
    lv_image_set_src(ui_Image3, &ui_img_settings_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 200);

    ui_WatchButotn = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_WatchButotn, 60);
    lv_obj_set_height(ui_WatchButotn, 60);
    lv_obj_set_x(ui_WatchButotn, 40);
    lv_obj_set_y(ui_WatchButotn, 140);
    lv_obj_add_flag(ui_WatchButotn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WatchButotn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WatchButotn, lv_color_hex(0xC2C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WatchButotn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_WatchButotn);
    lv_image_set_src(ui_Image4, &ui_img_1765884034);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 200);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    uic_MenuScreen = ui_MenuScreen;
    uic_WifiButton = ui_WifiButton;
    uic_MainScreenButton = ui_MainScreenButton;
    uic_SettingButotn = ui_SettingButotn;

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    uic_MenuScreen = NULL;
    ui_MenuScreen = NULL;
    uic_WifiButton = NULL;
    ui_WifiButton = NULL;
    ui_Image1 = NULL;
    uic_MainScreenButton = NULL;
    ui_MainScreenButton = NULL;
    ui_Image2 = NULL;
    uic_SettingButotn = NULL;
    ui_SettingButotn = NULL;
    ui_Image3 = NULL;
    ui_WatchButotn = NULL;
    ui_Image4 = NULL;

}
