// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "../ui.h"

lv_obj_t * uic_SliderValueLable;
lv_obj_t * uic_SettingScreen;
lv_obj_t * ui_SettingScreen;
lv_obj_t * ui_Container;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_SliderValueLable;

// event funtions
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SliderValueLable, target, "", "");
    }
}

// build funtions

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container = lv_obj_create(ui_SettingScreen);
    lv_obj_remove_style_all(ui_Container);
    lv_obj_set_height(ui_Container, 50);
    lv_obj_set_width(ui_Container, lv_pct(100));
    lv_obj_set_align(ui_Container, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Brightness");

    ui_Slider1 = lv_slider_create(ui_SettingScreen);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Slider1, 30);
    lv_obj_set_width(ui_Slider1, lv_pct(70));
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SliderValueLable = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SliderValueLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderValueLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderValueLable, 0);
    lv_obj_set_y(ui_SliderValueLable, 40);
    lv_obj_set_align(ui_SliderValueLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderValueLable, "0");

    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    uic_SettingScreen = ui_SettingScreen;
    uic_SliderValueLable = ui_SliderValueLable;

}

void ui_SettingScreen_screen_destroy(void)
{
    if(ui_SettingScreen) lv_obj_del(ui_SettingScreen);

    // NULL screen variables
    uic_SettingScreen = NULL;
    ui_SettingScreen = NULL;
    ui_Container = NULL;
    ui_Label3 = NULL;
    ui_Slider1 = NULL;
    uic_SliderValueLable = NULL;
    ui_SliderValueLable = NULL;

}
