// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#ifndef UI_WIFISETTINGSCREEN_H
#define UI_WIFISETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSettingScreen
extern void ui_WifiSettingScreen_screen_init(void);
extern void ui_WifiSettingScreen_screen_destroy(void);
extern lv_obj_t * ui_WifiSettingScreen;
extern lv_obj_t * ui_HeaderContainer;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_BodyContainer;
extern lv_obj_t * ui_WifiNameDisplayContainer;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image5;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiSettingScreen;
extern lv_obj_t * uic_BodyContainer;
extern lv_obj_t * uic_WifiNameDisplayContainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

