// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: esp32_lcd_1_28_inch

#include "../ui.h"

lv_obj_t * uic_WifiNameDisplayContainer;
lv_obj_t * uic_BodyContainer;
lv_obj_t * uic_WifiSettingScreen;
lv_obj_t * ui_WifiSettingScreen;
lv_obj_t * ui_HeaderContainer;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_BodyContainer;
lv_obj_t * ui_WifiNameDisplayContainer;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Button8;

// event funtions
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiInfoEvent(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiSelected_Event(e);
    }
}

// build funtions

void ui_WifiSettingScreen_screen_init(void)
{
    ui_WifiSettingScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiSettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderContainer = lv_obj_create(ui_WifiSettingScreen);
    lv_obj_remove_style_all(ui_HeaderContainer);
    lv_obj_set_height(ui_HeaderContainer, 50);
    lv_obj_set_width(ui_HeaderContainer, lv_pct(100));
    lv_obj_set_x(ui_HeaderContainer, 1);
    lv_obj_set_y(ui_HeaderContainer, 0);
    lv_obj_set_align(ui_HeaderContainer, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_HeaderContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_HeaderContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HeaderContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HeaderContainer);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 70);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "WIFI");

    ui_Switch1 = lv_switch_create(ui_HeaderContainer);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 20);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_BodyContainer = lv_obj_create(ui_WifiSettingScreen);
    lv_obj_remove_style_all(ui_BodyContainer);
    lv_obj_set_height(ui_BodyContainer, 190);
    lv_obj_set_width(ui_BodyContainer, lv_pct(100));
    lv_obj_set_x(ui_BodyContainer, 0);
    lv_obj_set_y(ui_BodyContainer, 50);
    lv_obj_set_align(ui_BodyContainer, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_BodyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiNameDisplayContainer = lv_obj_create(ui_BodyContainer);
    lv_obj_remove_style_all(ui_WifiNameDisplayContainer);
    lv_obj_set_height(ui_WifiNameDisplayContainer, 30);
    lv_obj_set_width(ui_WifiNameDisplayContainer, lv_pct(80));
    lv_obj_set_align(ui_WifiNameDisplayContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiNameDisplayContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiNameDisplayContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiNameDisplayContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiNameDisplayContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiNameDisplayContainer, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiNameDisplayContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_WifiNameDisplayContainer);
    lv_obj_set_width(ui_Button7, 20);
    lv_obj_set_height(ui_Button7, 20);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Button7);
    lv_image_set_src(ui_Image5, &ui_img_info_png);
    lv_obj_set_width(ui_Image5, 20);
    lv_obj_set_height(ui_Image5, 20);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image5, 150);

    ui_Button8 = lv_button_create(ui_WifiNameDisplayContainer);
    lv_obj_set_width(ui_Button8, 160);
    lv_obj_set_height(ui_Button8, 20);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    uic_WifiSettingScreen = ui_WifiSettingScreen;
    uic_BodyContainer = ui_BodyContainer;
    uic_WifiNameDisplayContainer = ui_WifiNameDisplayContainer;

}

void ui_WifiSettingScreen_screen_destroy(void)
{
    if(ui_WifiSettingScreen) lv_obj_del(ui_WifiSettingScreen);

    // NULL screen variables
    uic_WifiSettingScreen = NULL;
    ui_WifiSettingScreen = NULL;
    ui_HeaderContainer = NULL;
    ui_Label1 = NULL;
    ui_Switch1 = NULL;
    uic_BodyContainer = NULL;
    ui_BodyContainer = NULL;
    uic_WifiNameDisplayContainer = NULL;
    ui_WifiNameDisplayContainer = NULL;
    ui_Button7 = NULL;
    ui_Image5 = NULL;
    ui_Button8 = NULL;

}
